// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/proto/cache_object_test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoTestObject struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       int64                  `protobuf:"varint,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProtoTestObject) Reset() {
	*x = ProtoTestObject{}
	mi := &file_internal_proto_cache_object_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTestObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTestObject) ProtoMessage() {}

func (x *ProtoTestObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cache_object_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoTestObject) GetValue() int64 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return 0
}

func (x *ProtoTestObject) SetValue(v int64) {
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ProtoTestObject) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProtoTestObject) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = 0
}

type ProtoTestObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *int64
}

func (b0 ProtoTestObject_builder) Build() *ProtoTestObject {
	m0 := &ProtoTestObject{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = *b.Value
	}
	return m0
}

var File_internal_proto_cache_object_test_proto protoreflect.FileDescriptor

const file_internal_proto_cache_object_test_proto_rawDesc = "" +
	"\n" +
	"&internal/proto/cache_object_test.proto\x12\x05proto\x1a!google/protobuf/go_features.proto\"'\n" +
	"\x0fProtoTestObject\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05valueB\x91\x01\n" +
	"\tcom.protoB\x14CacheObjectTestProtoP\x01Z2github.com/abema/crema/ext/protobuf/internal/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_internal_proto_cache_object_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_cache_object_test_proto_goTypes = []any{
	(*ProtoTestObject)(nil), // 0: proto.ProtoTestObject
}
var file_internal_proto_cache_object_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_cache_object_test_proto_init() }
func file_internal_proto_cache_object_test_proto_init() {
	if File_internal_proto_cache_object_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_cache_object_test_proto_rawDesc), len(file_internal_proto_cache_object_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_cache_object_test_proto_goTypes,
		DependencyIndexes: file_internal_proto_cache_object_test_proto_depIdxs,
		MessageInfos:      file_internal_proto_cache_object_test_proto_msgTypes,
	}.Build()
	File_internal_proto_cache_object_test_proto = out.File
	file_internal_proto_cache_object_test_proto_goTypes = nil
	file_internal_proto_cache_object_test_proto_depIdxs = nil
}
