// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/proto/cache_object.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoCacheObject struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version         int32                  `protobuf:"varint,1,opt,name=version"`
	xxx_hidden_SerializedValue []byte                 `protobuf:"bytes,2,opt,name=serialized_value,json=serializedValue"`
	xxx_hidden_ExpireAtMillis  int64                  `protobuf:"varint,3,opt,name=expire_at_millis,json=expireAtMillis"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProtoCacheObject) Reset() {
	*x = ProtoCacheObject{}
	mi := &file_internal_proto_cache_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCacheObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCacheObject) ProtoMessage() {}

func (x *ProtoCacheObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cache_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoCacheObject) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *ProtoCacheObject) GetSerializedValue() []byte {
	if x != nil {
		return x.xxx_hidden_SerializedValue
	}
	return nil
}

func (x *ProtoCacheObject) GetExpireAtMillis() int64 {
	if x != nil {
		return x.xxx_hidden_ExpireAtMillis
	}
	return 0
}

func (x *ProtoCacheObject) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ProtoCacheObject) SetSerializedValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SerializedValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ProtoCacheObject) SetExpireAtMillis(v int64) {
	x.xxx_hidden_ExpireAtMillis = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ProtoCacheObject) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProtoCacheObject) HasSerializedValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProtoCacheObject) HasExpireAtMillis() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProtoCacheObject) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = 0
}

func (x *ProtoCacheObject) ClearSerializedValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SerializedValue = nil
}

func (x *ProtoCacheObject) ClearExpireAtMillis() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExpireAtMillis = 0
}

type ProtoCacheObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version         *int32
	SerializedValue []byte
	ExpireAtMillis  *int64
}

func (b0 ProtoCacheObject_builder) Build() *ProtoCacheObject {
	m0 := &ProtoCacheObject{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Version = *b.Version
	}
	if b.SerializedValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SerializedValue = b.SerializedValue
	}
	if b.ExpireAtMillis != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ExpireAtMillis = *b.ExpireAtMillis
	}
	return m0
}

var File_internal_proto_cache_object_proto protoreflect.FileDescriptor

const file_internal_proto_cache_object_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/cache_object.proto\x12\x05proto\x1a!google/protobuf/go_features.proto\"\x81\x01\n" +
	"\x10ProtoCacheObject\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12)\n" +
	"\x10serialized_value\x18\x02 \x01(\fR\x0fserializedValue\x12(\n" +
	"\x10expire_at_millis\x18\x03 \x01(\x03R\x0eexpireAtMillisB\x8d\x01\n" +
	"\tcom.protoB\x10CacheObjectProtoP\x01Z2github.com/abema/crema/ext/protobuf/internal/proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_internal_proto_cache_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_cache_object_proto_goTypes = []any{
	(*ProtoCacheObject)(nil), // 0: proto.ProtoCacheObject
}
var file_internal_proto_cache_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_cache_object_proto_init() }
func file_internal_proto_cache_object_proto_init() {
	if File_internal_proto_cache_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_cache_object_proto_rawDesc), len(file_internal_proto_cache_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_cache_object_proto_goTypes,
		DependencyIndexes: file_internal_proto_cache_object_proto_depIdxs,
		MessageInfos:      file_internal_proto_cache_object_proto_msgTypes,
	}.Build()
	File_internal_proto_cache_object_proto = out.File
	file_internal_proto_cache_object_proto_goTypes = nil
	file_internal_proto_cache_object_proto_depIdxs = nil
}
